using System.Diagnostics;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace RepoConventions;

internal sealed class ConventionRunner
{
	private const string c_repoConventionsLabel = "repo-conventions";
	private const string c_repoConventionsLabelColor = "1d76db";
	private const string c_repoConventionsLabelDescription = "Pull requests generated by repo-conventions.";

	public ConventionRunner(ConventionRunnerSettings settings) => m_settings = settings;

	public async Task<int> RunAsync(string topLevelConfigPath, ApplyCommandSettings applySettings, CancellationToken cancellationToken)
	{
		try
		{
			var topLevelConfiguration = ConventionConfiguration.Load(topLevelConfigPath);

			PullRequestPreparation? pullRequest = null;
			if (applySettings.OpenPullRequest)
			{
				pullRequest = await PreparePullRequestAsync(cancellationToken);
				if (pullRequest is null)
					return 1;
			}

			return await RunLoadedConfigurationAsync(topLevelConfigPath, topLevelConfiguration, applySettings, pullRequest, cancellationToken);
		}
		catch (ProgramException ex)
		{
			await m_settings.StandardError.WriteLineAsync(ex.Message);
			return 1;
		}
	}

	public async Task<int> AddAsync(string topLevelConfigPath, string configurationDisplayPath, IReadOnlyList<string> conventionPaths, bool openPullRequest, CancellationToken cancellationToken)
	{
		try
		{
			PullRequestPreparation? pullRequest = null;
			if (openPullRequest)
			{
				pullRequest = await PreparePullRequestAsync(cancellationToken);
				if (pullRequest is null)
					return 1;
			}

			var addedConventionPaths = new List<string>();
			foreach (var conventionPath in conventionPaths)
			{
				if (ConventionConfiguration.AddConventionPath(topLevelConfigPath, conventionPath))
				{
					addedConventionPaths.Add(conventionPath);
					await m_settings.StandardOutput.WriteLineAsync($"Added convention path '{conventionPath}' to '{configurationDisplayPath}'.");
				}
				else
				{
					await m_settings.StandardOutput.WriteLineAsync($"Convention path '{conventionPath}' is already present in '{configurationDisplayPath}'.");
				}
			}

			if (pullRequest is null)
				return 0;

			if (addedConventionPaths.Count != 0)
				await m_settings.TargetGitClient.CommitAllAsync(BuildAddConventionsCommitMessage(addedConventionPaths), cancellationToken);

			var topLevelConfiguration = ConventionConfiguration.Load(topLevelConfigPath);
			return await RunLoadedConfigurationAsync(topLevelConfigPath, topLevelConfiguration, new ApplyCommandSettings(OpenPullRequest: true, Draft: null, AutoMerge: null, MergeMethod: null), pullRequest, cancellationToken);
		}
		catch (ProgramException ex)
		{
			await m_settings.StandardError.WriteLineAsync(ex.Message);
			return 1;
		}
	}

	private async Task<int> RunLoadedConfigurationAsync(string topLevelConfigPath, ConventionFileConfiguration topLevelConfiguration, ApplyCommandSettings applySettings, PullRequestPreparation? pullRequest, CancellationToken cancellationToken)
	{
		var planState = new ConventionPlanState();
		var plannedConventions = new List<PlannedConvention>();
		var planSucceeded = await BuildConventionPlanAsync(topLevelConfiguration.Conventions, topLevelConfigPath, allowPullRequestSettings: true, new HashSet<string>(StringComparer.Ordinal), planState, plannedConventions, parentSettings: null, enableSettingsExpressions: false, sourceConventionOccurrenceId: null, sourceConventionNames: Array.Empty<string>(), cancellationToken);
		if (!planSucceeded)
			return 1;

		if (pullRequest is { HasOpenPullRequest: true })
			await WriteExistingPullRequestPreparationMessageAsync(pullRequest);

		await m_settings.StandardOutput.WriteLineAsync($"Applying {plannedConventions.Count.ToString(CultureInfo.InvariantCulture)} conventions...");

		var appliedConventions = new List<AppliedConvention>();
		var success = await ApplyConventionPlanAsync(plannedConventions, appliedConventions, cancellationToken);
		if (!success)
			return 1;

		if (pullRequest is not null)
			return await CompletePullRequestAsync(pullRequest, topLevelConfigPath, topLevelConfiguration.PullRequest, applySettings, appliedConventions, cancellationToken);

		await WriteCommitSummaryAsync(appliedConventions.Sum(static x => x.CreatedCommitCount));
		return 0;
	}

	private async Task WriteExistingPullRequestPreparationMessageAsync(PullRequestPreparation pullRequest)
	{
		if (pullRequest.PullRequestUrl is null)
			throw new InvalidOperationException("Existing pull request URL was not provided.");

		var operation = pullRequest.RestartedFromBase ? "Rebuilding" : "Amending";
		await m_settings.StandardOutput.WriteLineAsync($"{operation} existing pull request: {pullRequest.PullRequestUrl}");
	}

	private static string BuildAddConventionsCommitMessage(List<string> addedConventionPaths) =>
		addedConventionPaths.Count == 1 ? $"Add convention {addedConventionPaths[0]}" : "Add repository conventions";

	private async Task<bool> BuildConventionPlanAsync(IReadOnlyList<ConventionReference> references, string configurationPath, bool allowPullRequestSettings, HashSet<string> activeConventions, ConventionPlanState planState, List<PlannedConvention> plannedConventions, JsonNode? parentSettings, bool enableSettingsExpressions, int? sourceConventionOccurrenceId, IReadOnlyList<string> sourceConventionNames, CancellationToken cancellationToken)
	{
		foreach (var reference in references)
		{
			if (!await AddConventionToPlanAsync(reference, configurationPath, allowPullRequestSettings, activeConventions, planState, plannedConventions, parentSettings, enableSettingsExpressions, sourceConventionOccurrenceId, sourceConventionNames, cancellationToken))
				return false;
		}

		return true;
	}

	private async Task<bool> BuildConventionPlanFromFileAsync(string configPath, HashSet<string> activeConventions, ConventionPlanState planState, List<PlannedConvention> plannedConventions, JsonNode? parentSettings, bool enableSettingsExpressions, int? sourceConventionOccurrenceId, IReadOnlyList<string> sourceConventionNames, CancellationToken cancellationToken)
	{
		var configuration = ConventionConfiguration.Load(configPath);
		return await BuildConventionPlanAsync(configuration.Conventions, configPath, ShouldAllowConventionPullRequestSettings(configPath), activeConventions, planState, plannedConventions, parentSettings, enableSettingsExpressions, sourceConventionOccurrenceId, sourceConventionNames, cancellationToken);
	}

	private async Task<bool> AddConventionToPlanAsync(ConventionReference reference, string configurationPath, bool allowPullRequestSettings, HashSet<string> activeConventions, ConventionPlanState planState, List<PlannedConvention> plannedConventions, JsonNode? parentSettings, bool enableSettingsExpressions, int? sourceConventionOccurrenceId, IReadOnlyList<string> sourceConventionNames, CancellationToken cancellationToken)
	{
		JsonNode? effectiveSettings;
		ResolvedConvention resolvedConvention;
		try
		{
			effectiveSettings = ConventionSettingsPropagator.Resolve(
				reference.Settings,
				new ConventionSettingsEvaluationContext(
					configurationPath,
					m_settings.TargetRepositoryRoot,
					parentSettings,
					enableSettingsExpressions,
					sourceConventionNames.Count > 0 ? sourceConventionNames[0] : "top-level",
					reference.Path));

			var containingDirectory = Path.GetDirectoryName(configurationPath)!;
			resolvedConvention = await ResolveConventionAsync(reference.Path, containingDirectory, cancellationToken);
		}
		catch (ProgramException ex)
		{
			await m_settings.StandardError.WriteLineAsync(ex.Message);
			return false;
		}

		if (activeConventions.Contains(resolvedConvention.Identity))
		{
			await m_settings.StandardOutput.WriteLineAsync($"Convention {resolvedConvention.DisplayName}: skipped (cycle detected).");
			return true;
		}

		if (!Directory.Exists(resolvedConvention.DirectoryPath))
		{
			await m_settings.StandardError.WriteLineAsync($"Convention '{reference.Path}' directory '{resolvedConvention.DirectoryPath}' was not found.");
			return false;
		}

		var conventionConfigPath = Path.Combine(resolvedConvention.DirectoryPath, "convention.yml");
		var conventionScriptPath = Path.Combine(resolvedConvention.DirectoryPath, "convention.ps1");
		var hasConfiguration = File.Exists(conventionConfigPath);
		var hasExecutableScript = File.Exists(conventionScriptPath);
		if (!hasConfiguration && !hasExecutableScript)
		{
			await m_settings.StandardError.WriteLineAsync($"Convention '{reference.Path}' did not contain convention.yml or convention.ps1.");
			return false;
		}

		var occurrenceId = planState.GetNextOccurrenceId();
		activeConventions.Add(resolvedConvention.Identity);
		try
		{
			if (hasConfiguration)
			{
				var childSourceConventionNames = BuildSourceConventionNames(resolvedConvention.DisplayName, sourceConventionNames);
				if (!await BuildConventionPlanFromFileAsync(conventionConfigPath, activeConventions, planState, plannedConventions, effectiveSettings, enableSettingsExpressions: true, occurrenceId, childSourceConventionNames, cancellationToken))
					return false;
			}

			plannedConventions.Add(new PlannedConvention(occurrenceId, resolvedConvention, effectiveSettings, allowPullRequestSettings ? reference.PullRequest : null, hasExecutableScript, sourceConventionOccurrenceId, sourceConventionNames));
			return true;
		}
		finally
		{
			activeConventions.Remove(resolvedConvention.Identity);
		}
	}

	private async Task<bool> ApplyConventionPlanAsync(IReadOnlyList<PlannedConvention> plannedConventions, List<AppliedConvention> appliedConventions, CancellationToken cancellationToken)
	{
		foreach (var plannedConvention in plannedConventions)
		{
			if (!await ApplyPlannedConventionAsync(plannedConvention, appliedConventions, cancellationToken))
				return false;
		}

		return true;
	}

	private async Task<bool> ApplyPlannedConventionAsync(PlannedConvention plannedConvention, List<AppliedConvention> appliedConventions, CancellationToken cancellationToken)
	{
		var startMessage = $"Convention {FormatApplyingConventionName(plannedConvention)}";
		var openedGitHubActionsGroup = m_settings.UseGitHubActionsGroupMarkers;
		string conventionResultMessage;
		if (openedGitHubActionsGroup)
		{
			await m_settings.StandardOutput.WriteLineAsync($"::group::{startMessage}");
		}
		else
		{
			await m_settings.StandardOutput.WriteLineAsync();
			await m_settings.StandardOutput.WriteLineAsync(startMessage);
		}

		try
		{
			var headBeforeConvention = await m_settings.TargetGitClient.GetHeadAsync(cancellationToken);
			var conventionScriptPath = Path.Combine(plannedConvention.ResolvedConvention.DirectoryPath, "convention.ps1");
			if (File.Exists(conventionScriptPath))
			{
				var scriptResult = await RunConventionScriptAsync(conventionScriptPath, plannedConvention.Settings, plannedConvention.ResolvedConvention.DisplayName, cancellationToken);
				if (!scriptResult.Succeeded)
					return false;
			}

			var createdCommitCount = await m_settings.TargetGitClient.CountCommitsSinceAsync(headBeforeConvention, cancellationToken);
			appliedConventions.Add(new AppliedConvention(
				plannedConvention.OccurrenceId,
				plannedConvention.ResolvedConvention.Identity,
				plannedConvention.ResolvedConvention.DisplayName,
				plannedConvention.ResolvedConvention.TargetRepositoryRelativePath,
				plannedConvention.ResolvedConvention.RemoteDirectory,
				plannedConvention.PullRequest,
				plannedConvention.HasExecutableScript,
				plannedConvention.SourceConventionOccurrenceId,
				createdCommitCount));
			conventionResultMessage = createdCommitCount switch
			{
				0 => $"No changes for convention {plannedConvention.ResolvedConvention.DisplayName}.",
				1 => $"Created 1 commit for convention {plannedConvention.ResolvedConvention.DisplayName}.",
				_ => $"Created {createdCommitCount} commits for convention {plannedConvention.ResolvedConvention.DisplayName}.",
			};
		}
		finally
		{
			if (openedGitHubActionsGroup)
				await m_settings.StandardOutput.WriteLineAsync("::endgroup::");
		}

		await m_settings.StandardOutput.WriteLineAsync(conventionResultMessage);
		return true;
	}

	private async Task<ConventionExecutionResult> RunConventionScriptAsync(string scriptPath, JsonNode? settings, string conventionName, CancellationToken cancellationToken)
	{
		var headBeforeConvention = await m_settings.TargetGitClient.GetHeadAsync(cancellationToken);
		string inputPath;
		try
		{
			inputPath = TemporaryPathFactory.CreateFile(m_settings.TempRoot, ".json");
		}
		catch (ProgramException ex)
		{
			await m_settings.StandardError.WriteLineAsync(ex.Message);
			return ConventionExecutionResult.Failed();
		}

		await File.WriteAllTextAsync(inputPath, JsonSerializer.Serialize(new JsonObject { ["settings"] = settings }), cancellationToken);

		try
		{
			var startInfo = new ProcessStartInfo("pwsh")
			{
				WorkingDirectory = m_settings.TargetRepositoryRoot,
				RedirectStandardError = true,
				RedirectStandardOutput = true,
				UseShellExecute = false,
			};
			startInfo.ArgumentList.Add("-NoProfile");
			startInfo.ArgumentList.Add("-File");
			startInfo.ArgumentList.Add(scriptPath);
			startInfo.ArgumentList.Add(inputPath);

			using var process = Process.Start(startInfo) ?? throw new ProgramException("Failed to start pwsh.");
			var outputTask = PumpOutputAsync(process.StandardOutput, m_settings.StandardOutput);
			var errorTask = PumpOutputAsync(process.StandardError, m_settings.StandardError);
			await process.WaitForExitAsync(cancellationToken);
			await Task.WhenAll(outputTask, errorTask);

			if (process.ExitCode != 0)
			{
				await m_settings.TargetGitClient.ResetHardAsync(headBeforeConvention, cancellationToken);
				await m_settings.StandardError.WriteLineAsync($"Convention {conventionName} failed.");
				return ConventionExecutionResult.Failed();
			}

			if (await m_settings.TargetGitClient.HasChangesAsync(cancellationToken))
			{
				await m_settings.TargetGitClient.CommitAllAsync($"Apply convention {conventionName}", cancellationToken);
			}

			return ConventionExecutionResult.Success();
		}
		finally
		{
			File.Delete(inputPath);
		}
	}

	private async Task<ResolvedConvention> ResolveConventionAsync(string conventionPath, string containingDirectory, CancellationToken cancellationToken)
	{
		var repositoryRoot = GetContainingRepositoryRoot(containingDirectory);

		if (conventionPath.StartsWith('/'))
		{
			var relativeConventionPath = conventionPath.TrimStart('/').Replace('/', Path.DirectorySeparatorChar);
			var directoryPath = ResolveLocalConventionDirectoryPath(repositoryRoot, relativeConventionPath, repositoryRoot);
			var name = new DirectoryInfo(directoryPath).Name;
			return new ResolvedConvention(directoryPath, name, directoryPath, GetTargetRepositoryRelativePath(directoryPath), null);
		}

		if (conventionPath.StartsWith("./", StringComparison.Ordinal) || conventionPath.StartsWith("../", StringComparison.Ordinal))
		{
			var directoryPath = ResolveLocalConventionDirectoryPath(containingDirectory, conventionPath, repositoryRoot);
			var name = new DirectoryInfo(directoryPath).Name;

			if (TryGetRemoteCloneContext(directoryPath, out var remoteRepository, out var remoteCloneRoot))
			{
				var remoteDirectoryPath = NormalizeGitHubPath(Path.GetRelativePath(remoteCloneRoot, directoryPath));
				return new ResolvedConvention(directoryPath, name, directoryPath, null, new RemoteDirectoryReference(remoteRepository.Owner, remoteRepository.Repository, remoteRepository.Ref, remoteDirectoryPath));
			}

			return new ResolvedConvention(directoryPath, name, directoryPath, GetTargetRepositoryRelativePath(directoryPath), null);
		}

		var remotePath = RemoteConventionPath.Parse(conventionPath);
		var cloneRoot = await GetOrCloneRemoteRepositoryAsync(remotePath, cancellationToken);
		var resolvedDirectoryPath = string.IsNullOrEmpty(remotePath.SubPath)
			? cloneRoot
			: Path.Combine(cloneRoot, remotePath.SubPath.Replace('/', Path.DirectorySeparatorChar));
		var displayName = string.IsNullOrEmpty(remotePath.SubPath)
			? remotePath.Repository
			: new DirectoryInfo(resolvedDirectoryPath).Name;
		return new ResolvedConvention(resolvedDirectoryPath, displayName, remotePath.Identity, null, new RemoteDirectoryReference(remotePath.Owner, remotePath.Repository, remotePath.Ref, remotePath.SubPath));
	}

	private async Task<string> GetOrCloneRemoteRepositoryAsync(RemoteConventionPath remotePath, CancellationToken cancellationToken)
	{
		if (m_remoteCloneCache.TryGetValue(remotePath.Identity, out var existingPath))
			return existingPath;

		var clonePath = TemporaryPathFactory.CreateDirectory(m_settings.TempRoot);
		var repositoryUrl = GetRemoteRepositoryUrl(remotePath);

		var cloneResult = await GitClient.RunGitAsync(m_settings.TargetRepositoryRoot, ["clone", repositoryUrl, clonePath], cancellationToken);
		if (cloneResult.ExitCode != 0)
			throw new ProgramException($"Failed to clone remote convention repository '{repositoryUrl}': {cloneResult.StandardError}{cloneResult.StandardOutput}");

		if (!string.IsNullOrEmpty(remotePath.Ref))
		{
			var checkoutResult = await GitClient.RunGitAsync(clonePath, ["checkout", remotePath.Ref], cancellationToken);
			if (checkoutResult.ExitCode != 0)
				throw new ProgramException($"Failed to checkout ref '{remotePath.Ref}' in '{repositoryUrl}': {checkoutResult.StandardError}{checkoutResult.StandardOutput}");
		}

		m_remoteCloneCache.Add(remotePath.Identity, clonePath);
		m_remoteRepositoryContexts[clonePath] = new RemoteRepositoryInfo(remotePath.Owner, remotePath.Repository, remotePath.Ref);
		return clonePath;
	}

	private string GetRemoteRepositoryUrl(RemoteConventionPath remotePath) =>
		m_settings.RemoteRepositoryUrlResolver?.Invoke(new RemoteRepositoryUrlRequest(remotePath.Owner, remotePath.Repository)) ?? $"https://github.com/{remotePath.Owner}/{remotePath.Repository}.git";

	private async Task<PullRequestPreparation?> PreparePullRequestAsync(CancellationToken cancellationToken)
	{
		var startingBranch = await m_settings.TargetGitClient.GetCurrentBranchAsync(cancellationToken);
		if (string.IsNullOrWhiteSpace(startingBranch))
		{
			await m_settings.StandardError.WriteLineAsync("repo-conventions must not be run from a detached HEAD when using --open-pr.");
			return null;
		}

		if (await m_settings.TargetGitClient.HasUnpushedCommitsAsync(cancellationToken))
		{
			await m_settings.StandardError.WriteLineAsync("repo-conventions must be run with no unpushed commits when using --open-pr.");
			return null;
		}

		var startingHead = await m_settings.TargetGitClient.GetHeadAsync(cancellationToken);

		var openPullRequests = await GetOpenPullRequestsAsync(cancellationToken);
		var matchingPullRequests = openPullRequests
			.Where(x => x.BaseRefName == startingBranch)
			.Where(x => TryParseConventionBranchSuffix(x.HeadRefName) is not null)
			.ToList();
		if (matchingPullRequests.Count > 1)
		{
			var urls = string.Join(", ", matchingPullRequests.Select(static x => x.Url));
			await m_settings.StandardError.WriteLineAsync($"Multiple repo-conventions pull requests are already open for {startingBranch}: {urls}");
			return null;
		}

		if (matchingPullRequests.Count == 1)
		{
			var matchingPullRequest = matchingPullRequests[0];
			if (await m_settings.TargetGitClient.BranchExistsAsync(matchingPullRequest.HeadRefName, cancellationToken))
				await m_settings.TargetGitClient.SwitchToExistingBranchAsync(matchingPullRequest.HeadRefName, cancellationToken);
			else
				await m_settings.TargetGitClient.SwitchToNewBranchAsync(matchingPullRequest.HeadRefName, cancellationToken);

			var existingBranchHead = await m_settings.TargetGitClient.GetHeadAsync(cancellationToken);
			var mergeBaseResult = await m_settings.TargetGitClient.TryGetMergeBaseAsync(startingBranch, matchingPullRequest.HeadRefName, cancellationToken);
			if (!mergeBaseResult.Succeeded)
			{
				await m_settings.StandardError.WriteLineAsync(BuildMergeBaseFailureMessage(startingBranch, matchingPullRequest.HeadRefName, mergeBaseResult));
				return null;
			}

			var shouldRestartFromBase = mergeBaseResult.MergeBase != startingHead;
			if (shouldRestartFromBase)
				await m_settings.TargetGitClient.ResetHardAsync(startingHead, cancellationToken);

			return new PullRequestPreparation(
				startingBranch,
				matchingPullRequest.HeadRefName,
				matchingPullRequest.Url,
				matchingPullRequest.Body,
				HasOpenPullRequest: true,
				ExistingBranchHead: existingBranchHead,
				ForcePushAfterUpdate: shouldRestartFromBase,
				RestartedFromBase: shouldRestartFromBase);
		}

		var openPullRequestBranches = openPullRequests
			.Select(x => x.HeadRefName)
			.Where(x => TryParseConventionBranchSuffix(x) is not null)
			.ToHashSet(StringComparer.Ordinal);

		for (var suffix = 1; ; suffix++)
		{
			var branchName = GetConventionBranchName(suffix);
			if (openPullRequestBranches.Contains(branchName))
				continue;

			var branchExists = await m_settings.TargetGitClient.BranchExistsAsync(branchName, cancellationToken);
			if (!branchExists)
			{
				await m_settings.TargetGitClient.SwitchToNewBranchAsync(branchName, cancellationToken);
				return new PullRequestPreparation(startingBranch, branchName, PullRequestUrl: null, ExistingPullRequestBody: "", HasOpenPullRequest: false, ExistingBranchHead: null, ForcePushAfterUpdate: false, RestartedFromBase: false);
			}
		}
	}

	private async Task<IReadOnlyList<GitHubPullRequest>> GetOpenPullRequestsAsync(CancellationToken cancellationToken)
	{
		var result = await RunExternalCommandAsync("gh", m_settings.TargetRepositoryRoot, ["pr", "list", "--state", "open", "--json", "url,headRefName,baseRefName,body"], cancellationToken);
		if (result.ExitCode != 0)
			throw new InvalidOperationException($"Failed to query pull requests with gh: {result.StandardError}{result.StandardOutput}");

		try
		{
			return JsonSerializer.Deserialize<IReadOnlyList<GitHubPullRequest>>(string.IsNullOrWhiteSpace(result.StandardOutput) ? "[]" : result.StandardOutput, s_pullRequestJsonSerializerOptions) ?? [];
		}
		catch (JsonException ex)
		{
			throw new InvalidOperationException($"Failed to parse pull requests from gh: {result.StandardOutput}{result.StandardError}", ex);
		}
	}

	private async Task<int> CompletePullRequestAsync(PullRequestPreparation pullRequest, string topLevelConfigPath, PullRequestSettings? repositoryPullRequestSettings, ApplyCommandSettings applySettings, IReadOnlyList<AppliedConvention> appliedConventions, CancellationToken cancellationToken)
	{
		var newCommits = await m_settings.TargetGitClient.RunAsync(["rev-list", "--count", $"{pullRequest.StartingBranch}..HEAD"], cancellationToken);
		if (newCommits.ExitCode != 0)
			throw new InvalidOperationException($"Failed to compare branches: {newCommits.StandardError}{newCommits.StandardOutput}");

		var pullRequestCommitCount = int.Parse(newCommits.StandardOutput.Trim(), CultureInfo.InvariantCulture);
		var createdCommitCount = await CountPullRequestCommitsCreatedByRunAsync(pullRequest, pullRequestCommitCount, cancellationToken);
		var repositoryInfo = await GetTargetRepositoryInfoAsync(cancellationToken);
		var targetRepositoryUrl = repositoryInfo.Url;
		var body = BuildPullRequestBody(appliedConventions, targetRepositoryUrl, pullRequest.BranchName, GetTargetRepositoryRelativePathOrNull(topLevelConfigPath));
		var behavior = BuildPullRequestBehavior(repositoryPullRequestSettings, appliedConventions, applySettings);
		if (pullRequest.HasOpenPullRequest)
			return await CompleteExistingPullRequestAsync(pullRequest, pullRequestCommitCount, createdCommitCount, body, behavior, repositoryInfo, cancellationToken);

		if (pullRequestCommitCount == 0)
		{
			await WriteCommitSummaryAsync(createdCommitCount);
			return 0;
		}

		if (!await EnsureRepositoryLabelsAsync(behavior.Labels, cancellationToken))
			return 1;

		await m_settings.TargetGitClient.PushBranchAsync(pullRequest.BranchName, force: false, cancellationToken);
		if (pullRequest.HasOpenPullRequest)
			return 0;

		await m_settings.StandardOutput.WriteLineAsync($"Opening pull request from {pullRequest.BranchName} to {pullRequest.StartingBranch}...");
		var createResult = await RunExternalCommandAsync("gh", m_settings.TargetRepositoryRoot, BuildCreatePullRequestArguments(pullRequest, body, behavior), cancellationToken);
		if (createResult.ExitCode != 0)
		{
			await m_settings.StandardError.WriteLineAsync($"Failed to create pull request: {createResult.StandardError}{createResult.StandardOutput}");
			return 1;
		}

		var pullRequestUrl = ExtractGitHubPullRequestUrl(createResult.StandardOutput, createResult.StandardError);
		if (pullRequestUrl is null)
		{
			await m_settings.StandardOutput.WriteLineAsync("Opened pull request.");
			await WritePullRequestCommitSummaryAsync(pullRequest, createdCommitCount, pullRequestUrl: null);
			return 0;
		}

		var autoMergeOutcome = await CompleteAutoMergeStepAsync(pullRequestUrl, behavior, repositoryInfo, cancellationToken);
		await WritePullRequestAnnouncementAsync("Opened pull request", pullRequestUrl, behavior, autoMergeOutcome);
		await WritePullRequestCommitSummaryAsync(pullRequest, createdCommitCount, pullRequestUrl);
		return autoMergeOutcome.ExitCode;
	}

	private async Task<int> CompleteExistingPullRequestAsync(PullRequestPreparation pullRequest, int pullRequestCommitCount, int createdCommitCount, string pullRequestBody, PullRequestBehavior behavior, TargetRepositoryInfo repositoryInfo, CancellationToken cancellationToken)
	{
		if (pullRequest.PullRequestUrl is null)
			throw new InvalidOperationException("Existing pull request URL was not provided.");

		var currentHead = await m_settings.TargetGitClient.GetHeadAsync(cancellationToken);
		var commitsChanged = pullRequest.ExistingBranchHead != currentHead;
		var bodyChanged = pullRequest.ExistingPullRequestBody != pullRequestBody;
		var shouldCommentAdditionalConventionCommits = commitsChanged && !pullRequest.RestartedFromBase;

		if (pullRequestCommitCount == 0)
		{
			var comment = "No convention commits remain.";
			if (!await AddPullRequestCommentAsync(pullRequest.PullRequestUrl, comment, cancellationToken))
				return 1;

			if (!await ClosePullRequestAsync(pullRequest.PullRequestUrl, cancellationToken))
				return 1;

			await m_settings.StandardOutput.WriteLineAsync($"Closed pull request: {pullRequest.PullRequestUrl}");
			await WritePullRequestCommitSummaryAsync(pullRequest, createdCommitCount, pullRequest.PullRequestUrl);
			return 0;
		}

		if (!await EnsureRepositoryLabelsAsync(behavior.Labels, cancellationToken))
			return 1;

		if (commitsChanged)
			await m_settings.TargetGitClient.PushBranchAsync(pullRequest.BranchName, pullRequest.ForcePushAfterUpdate, cancellationToken);

		if (shouldCommentAdditionalConventionCommits)
		{
			if (!await AddPullRequestCommentAsync(pullRequest.PullRequestUrl, pullRequestBody, cancellationToken))
				return 1;
		}
		else if (bodyChanged)
		{
			if (!await UpdatePullRequestBodyAsync(pullRequest.PullRequestUrl, pullRequestBody, cancellationToken))
				return 1;
		}

		if (!await EnsurePullRequestMetadataAsync(pullRequest.PullRequestUrl, behavior, cancellationToken))
			return 1;

		var autoMergeOutcome = await CompleteAutoMergeStepAsync(pullRequest.PullRequestUrl, behavior, repositoryInfo, cancellationToken);
		var shouldReportPullRequest = commitsChanged || bodyChanged || ShouldReportPullRequestAnnouncement(behavior, autoMergeOutcome);
		if (shouldReportPullRequest)
			await WritePullRequestAnnouncementAsync("Updated pull request", pullRequest.PullRequestUrl, behavior, autoMergeOutcome);

		await WritePullRequestCommitSummaryAsync(pullRequest, createdCommitCount, pullRequest.PullRequestUrl);
		return autoMergeOutcome.ExitCode;
	}

	private async Task<int> CountPullRequestCommitsCreatedByRunAsync(PullRequestPreparation pullRequest, int pullRequestCommitCount, CancellationToken cancellationToken)
	{
		if (!pullRequest.HasOpenPullRequest || pullRequest.RestartedFromBase || pullRequest.ExistingBranchHead is null)
			return pullRequestCommitCount;

		return await m_settings.TargetGitClient.CountCommitsSinceAsync(pullRequest.ExistingBranchHead, cancellationToken);
	}

	private PullRequestBehavior BuildPullRequestBehavior(PullRequestSettings? repositoryPullRequestSettings, IReadOnlyList<AppliedConvention> appliedConventions, ApplyCommandSettings applySettings)
	{
		var contributingConventions = GetContributingConventions(appliedConventions);
		var draft = applySettings.Draft
			?? repositoryPullRequestSettings?.Draft
			?? contributingConventions.Any(static x => x.PullRequest?.Draft is true);

		bool autoMergeEnabled;
		if (applySettings.AutoMerge is { } cliAutoMerge)
		{
			autoMergeEnabled = cliAutoMerge;
		}
		else if (repositoryPullRequestSettings?.AutoMerge is { } repositoryAutoMerge)
		{
			autoMergeEnabled = repositoryAutoMerge;
		}
		else
		{
			var explicitConventionAutoMerge = contributingConventions
				.Where(static x => x.PullRequest?.AutoMerge is not null)
				.Select(static x => x.PullRequest!.AutoMerge!.Value)
				.ToList();

			if (explicitConventionAutoMerge.Contains(false))
			{
				autoMergeEnabled = false;
			}
			else if (explicitConventionAutoMerge.Contains(true))
			{
				autoMergeEnabled = true;
			}
			else if (contributingConventions.Count > 0 && contributingConventions.All(static x => !x.HasExecutableScript))
			{
				autoMergeEnabled = true;
			}
			else
			{
				autoMergeEnabled = false;
			}
		}

		var conventionMergeMethods = contributingConventions
			.Select(static x => x.PullRequest?.MergeMethod)
			.Where(static x => !string.IsNullOrWhiteSpace(x))
				.Select(ParseMergeMethod)
				.Distinct(StringComparer.Ordinal)
				.ToList();
		var mergeMethodConflictFallback = conventionMergeMethods.Count > 1 && applySettings.MergeMethod is null && string.IsNullOrWhiteSpace(repositoryPullRequestSettings?.MergeMethod);
		var desiredMergeMethod = applySettings.MergeMethod is { } cliMergeMethod
			? ParseMergeMethod(cliMergeMethod)
			: !string.IsNullOrWhiteSpace(repositoryPullRequestSettings?.MergeMethod)
				? ParseMergeMethod(repositoryPullRequestSettings!.MergeMethod!)
				: conventionMergeMethods.Count == 1
					? conventionMergeMethods[0]
					: "squash";

		var labels = new List<string>();
		AddUnique(labels, c_repoConventionsLabel, StringComparer.OrdinalIgnoreCase);
		AddUniqueRange(labels, repositoryPullRequestSettings?.Labels, StringComparer.OrdinalIgnoreCase);
		AddUniqueRange(labels, contributingConventions.SelectMany(static x => x.PullRequest?.Labels ?? []), StringComparer.OrdinalIgnoreCase);

		var reviewers = new List<string>();
		var assignees = new List<string>();
		if (!autoMergeEnabled)
		{
			AddUniqueRange(reviewers, repositoryPullRequestSettings?.Reviewers, StringComparer.OrdinalIgnoreCase);
			AddUniqueRange(reviewers, contributingConventions.SelectMany(static x => x.PullRequest?.Reviewers ?? []), StringComparer.OrdinalIgnoreCase);

			AddUniqueRange(assignees, repositoryPullRequestSettings?.Assignees, StringComparer.OrdinalIgnoreCase);
			AddUniqueRange(assignees, contributingConventions.SelectMany(static x => x.PullRequest?.Assignees ?? []), StringComparer.OrdinalIgnoreCase);
		}

		return new PullRequestBehavior(labels, reviewers, assignees, draft, autoMergeEnabled, desiredMergeMethod, mergeMethodConflictFallback, applySettings.AutoMerge is true);
	}

	private async Task WritePullRequestAnnouncementAsync(string message, string pullRequestUrl, PullRequestBehavior behavior, AutoMergeOutcome autoMergeOutcome)
	{
		var details = BuildPullRequestAnnouncementDetails(behavior, autoMergeOutcome);
		var suffix = details.Count == 0 ? "" : $" ({string.Join("; ", details)})";
		await m_settings.StandardOutput.WriteLineAsync($"{message}: {pullRequestUrl}{suffix}");
	}

	private async Task WriteCommitSummaryAsync(int commitCount) =>
		await m_settings.StandardOutput.WriteLineAsync(commitCount switch
		{
			0 => "No commits created.",
			1 => "Created 1 commit total.",
			_ => $"Created {commitCount.ToString(CultureInfo.InvariantCulture)} commits total.",
		});

	private async Task WritePullRequestCommitSummaryAsync(PullRequestPreparation pullRequest, int commitCount, string? pullRequestUrl)
	{
		if (pullRequest.HasOpenPullRequest && !pullRequest.RestartedFromBase && commitCount == 0 && pullRequestUrl is not null)
		{
			await m_settings.StandardOutput.WriteLineAsync($"No commits added to PR: {pullRequestUrl}");
			return;
		}

		var summary = commitCount switch
		{
			0 => "No commits created in PR",
			1 => "Created 1 commit in PR",
			_ => $"Created {commitCount.ToString(CultureInfo.InvariantCulture)} commits in PR",
		};

		await m_settings.StandardOutput.WriteLineAsync(pullRequestUrl is null ? $"{summary}." : $"{summary}: {pullRequestUrl}");
	}

	private static bool ShouldReportPullRequestAnnouncement(PullRequestBehavior behavior, AutoMergeOutcome autoMergeOutcome) =>
		BuildPullRequestAnnouncementDetails(behavior, autoMergeOutcome).Count != 0;

	private static List<string> BuildPullRequestAnnouncementDetails(PullRequestBehavior behavior, AutoMergeOutcome autoMergeOutcome)
	{
		var details = new List<string>();

		var reportedLabels = behavior.Labels
			.Where(static x => !string.Equals(x, c_repoConventionsLabel, StringComparison.OrdinalIgnoreCase))
			.ToList();
		if (reportedLabels.Count != 0)
			details.Add($"labels: {string.Join(", ", reportedLabels)}");

		if (!behavior.AutoMergeEnabled && behavior.Reviewers.Count != 0)
			details.Add($"reviewers: {string.Join(", ", behavior.Reviewers)}");

		if (!behavior.AutoMergeEnabled && behavior.Assignees.Count != 0)
			details.Add($"assignees: {string.Join(", ", behavior.Assignees)}");

		if (!string.IsNullOrWhiteSpace(autoMergeOutcome.Summary))
			details.Add(autoMergeOutcome.Summary);

		if (behavior.MergeMethodConflictFallback)
			details.Add("merge method conflict; defaulted to squash");

		return details;
	}

	private static List<string> BuildCreatePullRequestArguments(PullRequestPreparation pullRequest, string body, PullRequestBehavior behavior)
	{
		var arguments = new List<string>
		{
			"pr",
			"create",
			"--base",
			pullRequest.StartingBranch,
			"--head",
			pullRequest.BranchName,
			"--title",
			"Apply repository conventions",
		};

		if (behavior.Draft)
			arguments.Add("--draft");

		foreach (var label in behavior.Labels)
		{
			arguments.Add("--label");
			arguments.Add(label);
		}

		foreach (var reviewer in behavior.Reviewers)
		{
			arguments.Add("--reviewer");
			arguments.Add(reviewer);
		}

		foreach (var assignee in behavior.Assignees)
		{
			arguments.Add("--assignee");
			arguments.Add(assignee);
		}

		arguments.Add("--body");
		arguments.Add(body);

		return arguments;
	}

	private async Task<bool> EnsureRepositoryLabelsAsync(IReadOnlyList<string> labels, CancellationToken cancellationToken)
	{
		var existingLabels = await GetRepositoryLabelsAsync(cancellationToken);
		foreach (var label in labels)
		{
			if (existingLabels.Contains(label))
				continue;

			if (!await CreateRepositoryLabelAsync(label, cancellationToken))
				return false;

			existingLabels.Add(label);
		}

		return true;
	}

	private async Task<HashSet<string>> GetRepositoryLabelsAsync(CancellationToken cancellationToken)
	{
		var result = await RunExternalCommandAsync("gh", m_settings.TargetRepositoryRoot, ["label", "list", "--limit", "1000", "--json", "name"], cancellationToken);
		if (result.ExitCode != 0)
			throw new InvalidOperationException($"Failed to query labels with gh: {result.StandardError}{result.StandardOutput}");

		try
		{
			var labels = JsonSerializer.Deserialize<IReadOnlyList<GitHubLabel>>(string.IsNullOrWhiteSpace(result.StandardOutput) ? "[]" : result.StandardOutput, s_pullRequestJsonSerializerOptions) ?? [];
			return labels.Select(static x => x.Name).ToHashSet(StringComparer.OrdinalIgnoreCase);
		}
		catch (JsonException ex)
		{
			throw new InvalidOperationException($"Failed to parse labels from gh: {result.StandardOutput}{result.StandardError}", ex);
		}
	}

	private async Task<bool> CreateRepositoryLabelAsync(string label, CancellationToken cancellationToken)
	{
		var arguments = new List<string> { "label", "create", label };
		if (string.Equals(label, c_repoConventionsLabel, StringComparison.OrdinalIgnoreCase))
		{
			arguments.Add("--color");
			arguments.Add(c_repoConventionsLabelColor);
			arguments.Add("--description");
			arguments.Add(c_repoConventionsLabelDescription);
		}

		var result = await RunExternalCommandAsync("gh", m_settings.TargetRepositoryRoot, arguments, cancellationToken);
		if (result.ExitCode == 0)
			return true;

		await m_settings.StandardError.WriteLineAsync($"Failed to create label '{label}': {result.StandardError}{result.StandardOutput}");
		return false;
	}

	private async Task<bool> EnsurePullRequestMetadataAsync(string pullRequestUrl, PullRequestBehavior behavior, CancellationToken cancellationToken)
	{
		if (behavior.Labels.Count > 0 && !await EditPullRequestAsync(pullRequestUrl, behavior.Labels, "--add-label", "add labels", cancellationToken))
			return false;

		if (behavior.Reviewers.Count > 0 && !await EditPullRequestAsync(pullRequestUrl, behavior.Reviewers, "--add-reviewer", "add reviewers", cancellationToken))
			return false;

		if (behavior.Assignees.Count > 0 && !await EditPullRequestAsync(pullRequestUrl, behavior.Assignees, "--add-assignee", "add assignees", cancellationToken))
			return false;

		return true;
	}

	private async Task<bool> EditPullRequestAsync(string pullRequestUrl, IReadOnlyList<string> values, string flag, string operation, CancellationToken cancellationToken)
	{
		var arguments = new List<string> { "pr", "edit", pullRequestUrl };
		foreach (var value in values)
		{
			arguments.Add(flag);
			arguments.Add(value);
		}

		var result = await RunExternalCommandAsync("gh", m_settings.TargetRepositoryRoot, arguments, cancellationToken);
		if (result.ExitCode == 0)
			return true;

		await m_settings.StandardError.WriteLineAsync($"Failed to {operation} on pull request: {result.StandardError}{result.StandardOutput}");
		return false;
	}

	private async Task<AutoMergeOutcome> CompleteAutoMergeStepAsync(string pullRequestUrl, PullRequestBehavior behavior, TargetRepositoryInfo repositoryInfo, CancellationToken cancellationToken)
	{
		if (!behavior.AutoMergeEnabled)
			return AutoMergeOutcome.NotUsed();

		if (repositoryInfo.AutoMergeAllowed is false)
			return await HandleAutoMergeFailureAsync(behavior.AutoMergeRequestedExplicitly, "Auto-merge is not enabled for this repository.", "auto-merge, unavailable");

		var attemptedMethods = new HashSet<string>(StringComparer.Ordinal);
		string? fallbackReason = null;
		foreach (var method in GetMergeMethodAttemptOrder(behavior.DesiredMergeMethod))
		{
			if (!attemptedMethods.Add(method))
				continue;

			if (!IsMergeMethodAllowed(repositoryInfo, method))
			{
				fallbackReason ??= $"{FormatMergeMethodSummary(method)} disabled";
				continue;
			}

			var result = await TryEnableAutoMergeAsync(pullRequestUrl, method, cancellationToken);
			if (result.Succeeded)
				return AutoMergeOutcome.Success(method, fallbackReason);

			if (!result.ShouldTryNextMethod)
				return await HandleAutoMergeFailureAsync(behavior.AutoMergeRequestedExplicitly, result.ErrorMessage, BuildAutoMergeFailureSummary(fallbackReason, result.ErrorMessage));

			fallbackReason ??= SummarizeAutoMergeError(method, result.ErrorMessage);
		}

		return await HandleAutoMergeFailureAsync(behavior.AutoMergeRequestedExplicitly, $"Could not enable auto-merge using any allowed merge method for {pullRequestUrl}.", BuildAutoMergeFailureSummary(fallbackReason, null));
	}

	private async Task<AutoMergeOutcome> HandleAutoMergeFailureAsync(bool failCommand, string message, string summary)
	{
		if (failCommand)
		{
			await m_settings.StandardError.WriteLineAsync(message);
			return AutoMergeOutcome.Failed(summary);
		}

		return AutoMergeOutcome.Warning(summary);
	}

	private static string BuildAutoMergeFailureSummary(string? fallbackReason, string? errorMessage)
	{
		var reason = fallbackReason ?? SummarizeAutoMergeError(errorMessage);
		return string.IsNullOrWhiteSpace(reason) ? "auto-merge failed" : $"auto-merge, {reason}";
	}

	private static string SummarizeAutoMergeError(string method, string errorMessage)
	{
		var summary = SummarizeAutoMergeError(errorMessage);
		return string.IsNullOrWhiteSpace(summary) ? $"{FormatMergeMethodSummary(method)} failed" : summary;
	}

	private static string SummarizeAutoMergeError(string? errorMessage)
	{
		if (string.IsNullOrWhiteSpace(errorMessage))
			return "";

		var summary = errorMessage.Trim();
		var newlineIndex = summary.IndexOfAny(['\r', '\n']);
		if (newlineIndex >= 0)
			summary = summary[..newlineIndex];

		return summary.TrimEnd('.', ' ');
	}

	private static string FormatMergeMethodSummary(string method) => method switch
	{
		"merge" => "merge commit",
		"squash" => "squash",
		"rebase" => "rebase",
		_ => method,
	};

	private async Task<AutoMergeAttemptResult> TryEnableAutoMergeAsync(string pullRequestUrl, string method, CancellationToken cancellationToken)
	{
		var arguments = new List<string> { "pr", "merge", "--auto", pullRequestUrl, GetMergeMethodFlag(method) };
		var result = await RunExternalCommandAsync("gh", m_settings.TargetRepositoryRoot, arguments, cancellationToken);
		if (result.ExitCode == 0)
			return AutoMergeAttemptResult.Success();

		var errorMessage = string.Concat(result.StandardError, result.StandardOutput).Trim();
		return IsMergeMethodRejected(errorMessage)
			? AutoMergeAttemptResult.TryNext(errorMessage)
			: AutoMergeAttemptResult.Fail(errorMessage);
	}

	private static IEnumerable<string> GetMergeMethodAttemptOrder(string desiredMergeMethod)
	{
		yield return desiredMergeMethod;
		if (desiredMergeMethod != "squash")
			yield return "squash";
		if (desiredMergeMethod != "merge")
			yield return "merge";
		if (desiredMergeMethod != "rebase")
			yield return "rebase";
	}

	private static bool IsMergeMethodAllowed(TargetRepositoryInfo repositoryInfo, string method) => method switch
	{
		"merge" => repositoryInfo.MergeCommitAllowed is not false,
		"squash" => repositoryInfo.SquashMergeAllowed is not false,
		"rebase" => repositoryInfo.RebaseMergeAllowed is not false,
		_ => false,
	};

	private static string GetMergeMethodFlag(string method) => method switch
	{
		"merge" => "--merge",
		"squash" => "--squash",
		"rebase" => "--rebase",
		_ => throw new InvalidOperationException($"Unsupported merge method '{method}'."),
	};

	private static bool IsMergeMethodRejected(string errorMessage)
	{
		if (string.IsNullOrWhiteSpace(errorMessage))
			return false;

		return errorMessage.Contains("not allowed", StringComparison.OrdinalIgnoreCase)
			|| errorMessage.Contains("cannot be used", StringComparison.OrdinalIgnoreCase)
			|| errorMessage.Contains("disabled", StringComparison.OrdinalIgnoreCase);
	}

	private static string ParseMergeMethod(string? mergeMethod) => mergeMethod?.Trim().ToLowerInvariant() switch
	{
		"merge" => "merge",
		"squash" => "squash",
		"rebase" => "rebase",
		_ => throw new InvalidOperationException($"Unsupported pull request merge method '{mergeMethod}'."),
	};

	private static void AddUniqueRange(List<string> destination, IEnumerable<string>? values, StringComparer comparer)
	{
		if (values is null)
			return;

		foreach (var value in values)
			AddUnique(destination, value, comparer);
	}

	private static void AddUnique(List<string> destination, string value, StringComparer comparer)
	{
		if (string.IsNullOrWhiteSpace(value) || destination.Contains(value, comparer))
			return;

		destination.Add(value);
	}

	private bool ShouldAllowConventionPullRequestSettings(string configPath)
	{
		var containingDirectory = Path.GetDirectoryName(configPath)!;
		if (TryGetRemoteCloneContext(containingDirectory, out _, out _))
			return false;

		var relativePath = Path.GetRelativePath(m_settings.TargetRepositoryRoot, containingDirectory);
		return !relativePath.StartsWith("..", StringComparison.Ordinal) && !Path.IsPathRooted(relativePath);
	}

	private static string BuildPullRequestBody(IReadOnlyList<AppliedConvention> appliedConventions, string? targetRepositoryUrl, string branchName, string? configurationRepositoryRelativePath)
	{
		var visibleConventions = GetPullRequestBodyConventions(appliedConventions);
		var lines = new List<string>
		{
			$"{FormatConventionsLabel(targetRepositoryUrl, branchName, configurationRepositoryRelativePath)} applied by [repo-conventions](https://github.com/Faithlife/RepoConventions):",
		};

		lines.AddRange(RenderAppliedConventionLines(visibleConventions, targetRepositoryUrl, branchName));
		return string.Join(Environment.NewLine, lines);
	}

	private static List<AppliedConvention> GetContributingConventions(IReadOnlyList<AppliedConvention> appliedConventions) =>
		appliedConventions.Where(static x => x.CreatedCommitCount > 0).ToList();

	private static List<AppliedConvention> GetPullRequestBodyConventions(IReadOnlyList<AppliedConvention> appliedConventions)
	{
		var visibleConventionOccurrenceIds = new HashSet<int>();
		var conventionsByOccurrenceId = appliedConventions.ToDictionary(static x => x.OccurrenceId);

		foreach (var convention in GetContributingConventions(appliedConventions))
		{
			for (var currentConvention = convention;
				visibleConventionOccurrenceIds.Add(currentConvention.OccurrenceId) && currentConvention.SourceConventionOccurrenceId is { } parentOccurrenceId && conventionsByOccurrenceId.TryGetValue(parentOccurrenceId, out currentConvention);
			)
			{
			}
		}

		return appliedConventions.Where(x => visibleConventionOccurrenceIds.Contains(x.OccurrenceId)).ToList();
	}

	private static IEnumerable<string> RenderAppliedConventionLines(IReadOnlyList<AppliedConvention> appliedConventions, string? targetRepositoryUrl, string branchName)
	{
		var nodes = appliedConventions.ToDictionary(static x => x.OccurrenceId, static x => new AppliedConventionNode(x));
		var roots = new List<AppliedConventionNode>();

		foreach (var convention in appliedConventions)
		{
			var node = nodes[convention.OccurrenceId];
			if (convention.SourceConventionOccurrenceId is { } sourceConventionOccurrenceId && nodes.TryGetValue(sourceConventionOccurrenceId, out var parent))
				parent.Children.Add(node);
			else
				roots.Add(node);
		}

		foreach (var root in roots)
		{
			foreach (var line in RenderAppliedConventionNode(root, targetRepositoryUrl, branchName, depth: 0))
				yield return line;
		}
	}

	private static IEnumerable<string> RenderAppliedConventionNode(AppliedConventionNode node, string? targetRepositoryUrl, string branchName, int depth)
	{
		yield return $"{new string(' ', depth * 2)}- {FormatAppliedConvention(node.Convention, targetRepositoryUrl, branchName)}";

		foreach (var child in node.Children)
		{
			foreach (var line in RenderAppliedConventionNode(child, targetRepositoryUrl, branchName, depth + 1))
				yield return line;
		}
	}

	private static string FormatApplyingConventionName(PlannedConvention plannedConvention) =>
		plannedConvention.SourceConventionNames.Count == 0
			? plannedConvention.ResolvedConvention.DisplayName
			: $"{plannedConvention.ResolvedConvention.DisplayName} < {string.Join(" < ", plannedConvention.SourceConventionNames)}";

	private static string[] BuildSourceConventionNames(string sourceConventionName, IReadOnlyList<string> sourceConventionNames) =>
		[sourceConventionName, .. sourceConventionNames];

	private static string BuildMergeBaseFailureMessage(string startingBranch, string pullRequestBranch, GitMergeBaseResult mergeBaseResult)
	{
		var lines = new List<string>
		{
			$"repo-conventions could not compare '{startingBranch}' with existing pull request branch '{pullRequestBranch}'.",
			$"git merge-base {startingBranch} {pullRequestBranch} failed.",
		};

		var gitOutput = string.Concat(mergeBaseResult.CommandResult.StandardError, mergeBaseResult.CommandResult.StandardOutput).Trim();
		if (!string.IsNullOrEmpty(gitOutput))
			lines.Add($"git output: {gitOutput}");

		if (mergeBaseResult.IsShallowRepository)
		{
			lines.Add("This repository appears to be a shallow clone.");
			lines.Add("Suggested fixes: use actions/checkout with fetch-depth: 0, or run 'git fetch --prune --unshallow origin' before 'repo-conventions apply --open-pr'.");
		}
		else
		{
			lines.Add("Suggested fixes: fetch enough history for both branches, fetch the existing repo-conventions branch locally, or delete any stale local repo-conventions branch before rerunning.");
		}

		return string.Join(Environment.NewLine, lines);
	}

	private async Task<bool> AddPullRequestCommentAsync(string pullRequestUrl, string body, CancellationToken cancellationToken)
	{
		var result = await RunExternalCommandAsync("gh", m_settings.TargetRepositoryRoot, ["pr", "comment", pullRequestUrl, "--body", body], cancellationToken);
		if (result.ExitCode == 0)
			return true;

		await m_settings.StandardError.WriteLineAsync($"Failed to add pull request comment: {result.StandardError}{result.StandardOutput}");
		return false;
	}

	private async Task<bool> UpdatePullRequestBodyAsync(string pullRequestUrl, string body, CancellationToken cancellationToken)
	{
		var result = await RunExternalCommandAsync("gh", m_settings.TargetRepositoryRoot, ["pr", "edit", pullRequestUrl, "--body", body], cancellationToken);
		if (result.ExitCode == 0)
			return true;

		await m_settings.StandardError.WriteLineAsync($"Failed to update pull request body: {result.StandardError}{result.StandardOutput}");
		return false;
	}

	private async Task<bool> ClosePullRequestAsync(string pullRequestUrl, CancellationToken cancellationToken)
	{
		var result = await RunExternalCommandAsync("gh", m_settings.TargetRepositoryRoot, ["pr", "close", pullRequestUrl], cancellationToken);
		if (result.ExitCode == 0)
			return true;

		await m_settings.StandardError.WriteLineAsync($"Failed to close pull request: {result.StandardError}{result.StandardOutput}");
		return false;
	}

	private static async Task PumpOutputAsync(StreamReader reader, TextWriter writer)
	{
		while (await reader.ReadLineAsync() is { } line)
			await writer.WriteLineAsync(line);
	}

	private static string FormatConventionsLabel(string? targetRepositoryUrl, string branchName, string? configurationRepositoryRelativePath)
	{
		if (targetRepositoryUrl is null || string.IsNullOrEmpty(configurationRepositoryRelativePath))
			return "Conventions";

		return $"[Conventions]({targetRepositoryUrl}/blob/{branchName}/{configurationRepositoryRelativePath})";
	}

	private string? GetTargetRepositoryRelativePathOrNull(string path)
	{
		var relativePath = Path.GetRelativePath(m_settings.TargetRepositoryRoot, path);
		if (relativePath.StartsWith("..", StringComparison.Ordinal) || Path.IsPathRooted(relativePath))
			return null;

		return NormalizeGitHubPath(relativePath);
	}

	private static string FormatAppliedConvention(AppliedConvention convention, string? targetRepositoryUrl, string branchName)
	{
		var url = BuildAppliedConventionUrl(convention, targetRepositoryUrl, branchName);
		return url is null ? convention.DisplayName : $"[{convention.DisplayName}]({url})";
	}

	private static string? BuildAppliedConventionUrl(AppliedConvention convention, string? targetRepositoryUrl, string branchName)
	{
		if (convention.TargetRepositoryRelativePath is { } targetRepositoryRelativePath && targetRepositoryUrl is not null)
			return $"{targetRepositoryUrl}/tree/{branchName}/{targetRepositoryRelativePath}";

		if (convention.RemoteDirectory is { } remoteDirectory)
		{
			var repositoryUrl = $"https://github.com/{remoteDirectory.Owner}/{remoteDirectory.Repository}";
			if (string.IsNullOrEmpty(remoteDirectory.DirectoryPath))
				return remoteDirectory.Ref is null ? repositoryUrl : $"{repositoryUrl}/tree/{remoteDirectory.Ref}";

			return $"{repositoryUrl}/tree/{remoteDirectory.Ref ?? "HEAD"}/{remoteDirectory.DirectoryPath}";
		}

		return null;
	}

	private static string NormalizeGitHubPath(string path) => path.Replace(Path.DirectorySeparatorChar, '/');

	private string GetContainingRepositoryRoot(string containingDirectory) =>
		TryGetRemoteCloneContext(containingDirectory, out _, out var cloneRoot)
			? Path.GetFullPath(cloneRoot)
			: Path.GetFullPath(m_settings.TargetRepositoryRoot);

	private static string ResolveLocalConventionDirectoryPath(string baseDirectory, string conventionPath, string repositoryRoot)
	{
		var directoryPath = Path.GetFullPath(Path.Combine(baseDirectory, conventionPath));
		if (!IsWithinRepositoryRoot(directoryPath, repositoryRoot))
			throw new ProgramException($"Resolved convention path '{directoryPath}' escapes the repository root '{repositoryRoot}'.");

		return directoryPath;
	}

	private static bool IsWithinRepositoryRoot(string path, string repositoryRoot)
	{
		var comparison = OperatingSystem.IsWindows() ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal;
		var normalizedRoot = Path.TrimEndingDirectorySeparator(repositoryRoot);
		if (string.Equals(path, normalizedRoot, comparison))
			return true;

		return path.StartsWith(normalizedRoot + Path.DirectorySeparatorChar, comparison)
			|| path.StartsWith(normalizedRoot + Path.AltDirectorySeparatorChar, comparison);
	}

	private string GetTargetRepositoryRelativePath(string directoryPath) => NormalizeGitHubPath(Path.GetRelativePath(m_settings.TargetRepositoryRoot, directoryPath));

	private bool TryGetRemoteCloneContext(string directoryPath, out RemoteRepositoryInfo remoteRepository, out string cloneRoot)
	{
		foreach (var candidate in m_remoteRepositoryContexts.OrderByDescending(static x => x.Key.Length))
		{
			var relativePath = Path.GetRelativePath(candidate.Key, directoryPath);
			if (!relativePath.StartsWith("..", StringComparison.Ordinal) && !Path.IsPathRooted(relativePath))
			{
				remoteRepository = candidate.Value;
				cloneRoot = candidate.Key;
				return true;
			}
		}

		remoteRepository = null!;
		cloneRoot = null!;
		return false;
	}

	private async Task<TargetRepositoryInfo> GetTargetRepositoryInfoAsync(CancellationToken cancellationToken)
	{
		var result = await RunExternalCommandAsync("gh", m_settings.TargetRepositoryRoot, ["repo", "view", "--json", "url,autoMergeAllowed,mergeCommitAllowed,rebaseMergeAllowed,squashMergeAllowed"], cancellationToken);
		if (result.ExitCode != 0)
			return new TargetRepositoryInfo(null, null, null, null, null);

		var rawOutput = result.StandardOutput.Trim();
		if (Uri.TryCreate(rawOutput, UriKind.Absolute, out _))
			return new TargetRepositoryInfo(rawOutput, null, null, null, null);

		try
		{
			return JsonSerializer.Deserialize<TargetRepositoryInfo>(string.IsNullOrWhiteSpace(rawOutput) ? "{}" : rawOutput, s_pullRequestJsonSerializerOptions) ?? new TargetRepositoryInfo(null, null, null, null, null);
		}
		catch (JsonException)
		{
			return new TargetRepositoryInfo(ExtractGitHubPullRequestUrl(result.StandardOutput, result.StandardError) ?? rawOutput, null, null, null, null);
		}
	}

	private static string? ExtractGitHubPullRequestUrl(string standardOutput, string standardError)
	{
		foreach (var token in string.Concat(standardOutput, " ", standardError).Split((char[]?) null, StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
		{
			if (Uri.TryCreate(token, UriKind.Absolute, out var uri) &&
				string.Equals(uri.Scheme, Uri.UriSchemeHttps, StringComparison.OrdinalIgnoreCase) &&
				string.Equals(uri.Host, "github.com", StringComparison.OrdinalIgnoreCase))
			{
				return uri.AbsoluteUri;
			}
		}

		return null;
	}

	private static string GetConventionBranchName(int suffix) => suffix == 1 ? "repo-conventions" : $"repo-conventions-{suffix}";

	private static int? TryParseConventionBranchSuffix(string branchName)
	{
		if (branchName == "repo-conventions")
			return 1;

		const string prefix = "repo-conventions-";
		if (!branchName.StartsWith(prefix, StringComparison.Ordinal))
			return null;

		return int.TryParse(branchName[prefix.Length..], out var suffix) && suffix >= 2 ? suffix : null;
	}

	private async Task<ExternalCommandResult> RunExternalCommandAsync(string fileName, string workingDirectory, IReadOnlyList<string> arguments, CancellationToken cancellationToken)
	{
		if (m_settings.ExternalCommandRunner is { } externalCommandRunner)
			return await externalCommandRunner(new ExternalCommandRequest(fileName, workingDirectory, arguments), cancellationToken);

		return await RunExternalCommandCoreAsync(fileName, workingDirectory, arguments, cancellationToken);
	}

	private static async Task<ExternalCommandResult> RunExternalCommandCoreAsync(string fileName, string workingDirectory, IReadOnlyList<string> arguments, CancellationToken cancellationToken)
	{
		var startInfo = new ProcessStartInfo(fileName)
		{
			WorkingDirectory = workingDirectory,
			RedirectStandardError = true,
			RedirectStandardOutput = true,
			UseShellExecute = false,
		};

		foreach (var argument in arguments)
			startInfo.ArgumentList.Add(argument);

		using var process = Process.Start(startInfo) ?? throw new ProgramException($"Failed to start {fileName}.");
		var standardOutput = await process.StandardOutput.ReadToEndAsync(cancellationToken);
		var standardError = await process.StandardError.ReadToEndAsync(cancellationToken);
		await process.WaitForExitAsync(cancellationToken);

		return new ExternalCommandResult(process.ExitCode, standardOutput, standardError);
	}

	private sealed record ConventionExecutionResult(bool Succeeded)
	{
		public static ConventionExecutionResult Failed() => new(false);

		public static ConventionExecutionResult Success() => new(true);
	}

	private sealed record GitHubPullRequest(string Url, string HeadRefName, string BaseRefName, string Body);

	private sealed record PullRequestPreparation(string StartingBranch, string BranchName, string? PullRequestUrl, string ExistingPullRequestBody, bool HasOpenPullRequest, string? ExistingBranchHead, bool ForcePushAfterUpdate, bool RestartedFromBase);

	private sealed record PlannedConvention(int OccurrenceId, ResolvedConvention ResolvedConvention, JsonNode? Settings, PullRequestSettings? PullRequest, bool HasExecutableScript, int? SourceConventionOccurrenceId, IReadOnlyList<string> SourceConventionNames);

	private sealed record AppliedConvention(int OccurrenceId, string Identity, string DisplayName, string? TargetRepositoryRelativePath, RemoteDirectoryReference? RemoteDirectory, PullRequestSettings? PullRequest, bool HasExecutableScript, int? SourceConventionOccurrenceId, int CreatedCommitCount);

	private sealed record PullRequestBehavior(IReadOnlyList<string> Labels, IReadOnlyList<string> Reviewers, IReadOnlyList<string> Assignees, bool Draft, bool AutoMergeEnabled, string DesiredMergeMethod, bool MergeMethodConflictFallback, bool AutoMergeRequestedExplicitly);

	private sealed record AutoMergeOutcome(int ExitCode, string? Summary)
	{
		public static AutoMergeOutcome Failed(string summary) => new(1, summary);

		public static AutoMergeOutcome NotUsed() => new(0, null);

		public static AutoMergeOutcome Success(string method, string? fallbackReason)
		{
			var summary = string.IsNullOrWhiteSpace(fallbackReason)
				? $"auto-merge, {FormatMergeMethodSummary(method)}"
				: $"auto-merge, {FormatMergeMethodSummary(method)}, {fallbackReason}";
			return new(0, summary);
		}

		public static AutoMergeOutcome Warning(string summary) => new(0, summary);
	}

	private sealed record AutoMergeAttemptResult(bool Succeeded, bool ShouldTryNextMethod, string ErrorMessage)
	{
		public static AutoMergeAttemptResult Fail(string errorMessage) => new(false, false, errorMessage);

		public static AutoMergeAttemptResult Success() => new(true, false, "");

		public static AutoMergeAttemptResult TryNext(string errorMessage) => new(false, true, errorMessage);
	}

	private sealed record GitHubLabel(string Name);

	private sealed record TargetRepositoryInfo(string? Url, bool? AutoMergeAllowed, bool? MergeCommitAllowed, bool? RebaseMergeAllowed, bool? SquashMergeAllowed);

	private sealed class AppliedConventionNode(AppliedConvention convention)
	{
		public AppliedConvention Convention { get; } = convention;

		public List<AppliedConventionNode> Children { get; } = [];
	}

	private sealed class ConventionPlanState
	{
		public int GetNextOccurrenceId() => m_nextOccurrenceId++;

		private int m_nextOccurrenceId;
	}

	private sealed record RemoteDirectoryReference(string Owner, string Repository, string? Ref, string DirectoryPath);

	private sealed record RemoteRepositoryInfo(string Owner, string Repository, string? Ref);

	private sealed record ResolvedConvention(string DirectoryPath, string DisplayName, string Identity, string? TargetRepositoryRelativePath, RemoteDirectoryReference? RemoteDirectory);

	private sealed record RemoteConventionPath(string Owner, string Repository, string SubPath, string? Ref)
	{
		public string Identity => $"{Owner}/{Repository}:{SubPath}@{Ref}";

		public static RemoteConventionPath Parse(string conventionPath)
		{
			var refSeparatorIndex = conventionPath.LastIndexOf('@');
			var pathWithoutRef = refSeparatorIndex >= 0 ? conventionPath[..refSeparatorIndex] : conventionPath;
			var reference = refSeparatorIndex >= 0 ? conventionPath[(refSeparatorIndex + 1)..] : null;

			var segments = pathWithoutRef.Split('/', StringSplitOptions.RemoveEmptyEntries);
			if (segments.Length < 2)
				throw new ProgramException($"Convention path '{conventionPath}' is not a valid remote convention path.");

			var owner = segments[0];
			var repository = segments[1];
			var subPath = segments.Length > 2 ? string.Join('/', segments.Skip(2)) : "";
			return new RemoteConventionPath(owner, repository, subPath, reference);
		}
	}

	private static readonly JsonSerializerOptions s_pullRequestJsonSerializerOptions = new()
	{
		PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
	};

	private readonly ConventionRunnerSettings m_settings;
	private readonly Dictionary<string, string> m_remoteCloneCache = new(StringComparer.Ordinal);
	private readonly Dictionary<string, RemoteRepositoryInfo> m_remoteRepositoryContexts = new(StringComparer.Ordinal);
}
